- name: Instalacja i konfiguracja vsftpd
  hosts: all
  become: yes
  tasks:
    - name: Instalacja vsftpd
      ansible.builtin.dnf:
        name: vsftpd
        state: present

    - name: Uruchomienie i włączenie vsftpd przy starcie
      ansible.builtin.systemd:
        name: vsftpd
        enabled: yes
        state: started

    - name: Konfiguracja firewalld - dodanie usługi FTP
      ansible.posix.firewalld:
        service: ftp
        permanent: yes
        state: enabled
      notify: Restart firewalld

    - name: Upewnienie się, że katalog /var/ftp/pub istnieje
      ansible.builtin.file:
        path: /var/ftp/pub
        state: directory
        mode: '0755'

    - name: Kopiowanie plików do katalogu /var/ftp/pub
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/var/ftp/pub/{{ item }}"
        mode: '0644'
      loop:
        - plik1.txt
        - plik2.txt

    - name: Modyfikacja pliku konfiguracyjnego vsftpd
      ansible.builtin.lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable='
        line: 'anonymous_enable=YES'
      notify: Restart vsftpd

  handlers:
    - name: Restart vsftpd
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted

    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded