- name: Instalacja pakietów na Gdańsku
  hosts: gdansk
  become: yes
  tasks:
    - name: Instalacja pakietów dla Gdańska
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

- name: Instalacja pakietów na Poznaniu
  hosts: poznan
  become: yes
  tasks:
    - name: Instalacja pakietów dla Poznania
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

- name: Instalacja pakietów na wszystkich hostach
  hosts: all
  become: yes
  tasks:
    - name: Instalacja pakietów wspólnych - metoda 1 (cała lista)
      ansible.builtin.dnf:
        name: "{{ common_packages }}"
        state: present

    - name: Instalacja pakietów wspólnych - metoda 2 (pętla)
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ common_packages }}"