---
- name: Instalacja i konfiguracja vsftpd
  hosts: all
  become: yes
  tasks:

    - name: Instalacja vsftpd
      yum:
        name: vsftpd
        state: present

    - name: Uruchomienie i włączenie vsftpd przy starcie systemu
      service:
        name: vsftpd
        state: started
        enabled: yes

    - name: Tworzenie kopii zapasowej obecnego pliku konfiguracyjnego
      copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bak
        remote_src: yes
      when: ansible_facts['os_family'] == "RedHat"  # Można dostosować do innych systemów

    - name: Modyfikacja pliku konfiguracyjnego vsftpd
      copy:
        src: files/vsftpd.conf  # Plik z nową konfiguracją
        dest: /etc/vsftpd/vsftpd.conf
        backup: yes
      notify: Restart vsftpd
      register: vsftpd_config

    - name: Konfiguracja firewalld - dodanie usługi FTP
      firewalld:
        service: ftp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_facts['os_family'] == "RedHat"

  handlers:
    - name: Restart vsftpd
      service:
        name: vsftpd
        state: restarted
      when: vsftpd_config.changed

    - name: Przywrócenie poprzedniego pliku konfiguracyjnego w razie problemów
      copy:
        src: /etc/vsftpd/vsftpd.conf.bak
        dest: /etc/vsftpd/vsftpd.conf
        remote_src: yes
      notify: Restart vsftpd
      when: vsftpd_config.failed