---
- name: Instalacja i konfiguracja vsftpd
  hosts: all
  become: yes
  tasks:
    - name: Instalacja vsftpd
      ansible.builtin.dnf:
        name: vsftpd
        state: present

    - name: Uruchomienie i włączenie vsftpd przy starcie
      ansible.builtin.systemd:
        name: vsftpd
        enabled: yes
        state: started

    - name: Konfiguracja firewalld - dodanie usługi FTP
      ansible.builtin.firewalld:
        service: ftp
        permanent: yes
        state: enabled
      notify: Restart firewalld

    - name: Utworzenie plików w /var/ftp/pub
      ansible.builtin.copy:
        content: "To jest plik {{ item }}"
        dest: "/var/ftp/pub/{{ item }}"
        mode: '0644'
      loop:
        - plik1
        - plik2

    - name: Tworzenie kopii zapasowej pliku konfiguracyjnego vsftpd, jeśli istnieje
      ansible.builtin.copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: "/etc/vsftpd/vsftpd.conf.bak"
        backup: yes
      when: ansible_facts['os_family'] == "RedHat" and ansible.builtin.stat(path="/etc/vsftpd/vsftpd.conf").stat.exists

    - name: Przywrócenie domyślnego pliku konfiguracyjnego vsftpd.conf, jeśli nie istnieje
      ansible.builtin.copy:
        src: /usr/share/doc/vsftpd*/examples/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf
        remote_src: yes
      when: not ansible.builtin.stat(path="/etc/vsftpd/vsftpd.conf").stat.exists

    - name: Modyfikacja pliku konfiguracyjnego vsftpd
      ansible.builtin.lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable='
        line: 'anonymous_enable=YES'

    - name: Restart vsftpd tylko wtedy, gdy plik konfiguracyjny został zmieniony
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted
      when: ansible_facts['os_family'] == "RedHat" and ansible.builtin.stat(path="/etc/vsftpd/vsftpd.conf").stat.exists and ansible.builtin.stat(path="/etc/vsftpd/vsftpd.conf").stat.mtime != ansible.builtin.stat(path="/etc/vsftpd/vsftpd.conf.bak").stat.mtime

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded