- name: Instalacja i konfiguracja vsftpd
  hosts: all
  become: yes
  tasks:
    - name: Instalacja vsftpd
      ansible.builtin.dnf:
        name: vsftpd
        state: present

    - name: Uruchomienie i włączenie vsftpd przy starcie
      ansible.builtin.systemd:
        name: vsftpd
        enabled: yes
        state: started

    - name: Konfiguracja firewalld - dodanie usługi FTP
      ansible.builtin.firewalld:
        service: ftp
        permanent: yes
        state: enabled
      notify: Restart firewalld

    - name: Sprawdzenie, czy plik konfiguracyjny istnieje
      stat:
        path: /etc/vsftpd/vsftpd.conf
      register: vsftpd_conf

    - name: Przywrócenie domyślnego pliku konfiguracyjnego, jeśli nie istnieje
      ansible.builtin.copy:
        src: /usr/share/doc/vsftpd*/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf
        remote_src: yes
      when: not vsftpd_conf.stat.exists

    - name: Kopia zapasowa pliku konfiguracyjnego przed zmianami
      ansible.builtin.copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bak
        remote_src: yes
      when: vsftpd_conf.stat.exists

    - name: Modyfikacja pliku konfiguracyjnego vsftpd
      ansible.builtin.lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable='
        line: 'anonymous_enable=YES'
      notify: Restart vsftpd

  handlers:
    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

    - name: Restart vsftpd
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted